<?php
/** Portable TypeRocket Galaxy path resolver generated by MakerMaker. */
$makerGalaxyFail = static function ( string $message ): void {
    fwrite( STDERR, "MakerMaker Galaxy configuration error: {$message}\n" );
    exit( 1 );
};
$makerGalaxyRealDirectory = static function ( string $path, string $label ) use ( $makerGalaxyFail ): string {
    if ( $path === '' || is_link( $path ) ) { $makerGalaxyFail( "{$label} is empty or symbolic: {$path}" ); }
    $resolved = realpath( $path );
    if ( $resolved === false || ! is_dir( $resolved ) ) { $makerGalaxyFail( "{$label} directory was not found: {$path}" ); }
    return $resolved;
};
$makerGalaxyAbsolute = static function ( string $path, string $root ): string {
    return str_starts_with( $path, DIRECTORY_SEPARATOR ) ? $path : $root . DIRECTORY_SEPARATOR . $path;
};
$makerGalaxyRootOverride = getenv( 'MAKERMAKER_GALAXY_WORDPRESS_ROOT' ) ?: '';
$makerGalaxyRoot = $makerGalaxyRootOverride === '' ? __DIR__ : $makerGalaxyAbsolute( $makerGalaxyRootOverride, __DIR__ );
$makerGalaxyRoot = $makerGalaxyRealDirectory( $makerGalaxyRoot, 'WordPress root' );
if ( ! is_file( $makerGalaxyRoot . '/wp-load.php' ) && ! is_file( $makerGalaxyRoot . '/wp-config.php' ) ) {
    $makerGalaxyFail( 'WordPress root lacks wp-load.php/wp-config.php: ' . $makerGalaxyRoot );
}
$makerGalaxySlug = 'makermaker';
$makerGalaxyNamespace = 'Maker\\MakerMaker';
$makerGalaxyPlugin = '';
if ( $makerGalaxySlug !== null ) {
    $makerGalaxyPlugin = getenv( 'MAKERMAKER_GALAXY_PLUGIN_PATH' ) ?: '';
    if ( $makerGalaxyPlugin !== '' ) {
        $makerGalaxyPlugin = $makerGalaxyAbsolute( $makerGalaxyPlugin, $makerGalaxyRoot );
    } else {
        $pluginMatches = [];
        foreach ( glob( $makerGalaxyRoot . '/*', GLOB_ONLYDIR ) ?: [] as $content ) {
            foreach ( [ 'plugins', 'mu-plugins' ] as $kind ) {
                $candidate = $content . '/' . $kind . '/' . $makerGalaxySlug;
                if ( is_dir( $candidate ) && ! is_link( $candidate ) ) {
                    $resolved = realpath( $candidate );
                    if ( $resolved !== false && ( $resolved === $makerGalaxyRoot || str_starts_with( $resolved, $makerGalaxyRoot . DIRECTORY_SEPARATOR ) ) ) {
                        $pluginMatches[$resolved] = true;
                    }
                }
            }
        }
        $pluginMatches = array_keys( $pluginMatches );
        if ( count( $pluginMatches ) === 0 ) { $makerGalaxyFail( 'Plugin was not found; set MAKERMAKER_GALAXY_PLUGIN_PATH.' ); }
        if ( count( $pluginMatches ) > 1 ) { $makerGalaxyFail( 'Plugin discovery is ambiguous; set MAKERMAKER_GALAXY_PLUGIN_PATH explicitly.' ); }
        $makerGalaxyPlugin = $pluginMatches[0];
    }
    $makerGalaxyPlugin = $makerGalaxyRealDirectory( $makerGalaxyPlugin, 'Plugin' );
}
$makerGalaxyTypeRocket = getenv( 'MAKERMAKER_GALAXY_TYPEROCKET_PATH' ) ?: '';
if ( $makerGalaxyTypeRocket !== '' ) {
    $makerGalaxyTypeRocket = $makerGalaxyAbsolute( $makerGalaxyTypeRocket, $makerGalaxyRoot );
} else {
    $typeRocketMatches = [];
    foreach ( glob( $makerGalaxyRoot . '/*', GLOB_ONLYDIR ) ?: [] as $content ) {
        foreach ( [ 'plugins', 'mu-plugins' ] as $kind ) {
            foreach ( glob( $content . '/' . $kind . '/*', GLOB_ONLYDIR ) ?: [] as $package ) {
                foreach ( [ $package, $package . '/typerocket' ] as $candidate ) {
                    if ( is_file( $candidate . '/init.php' ) && is_dir( $candidate . '/vendor/typerocket/core' ) && ! is_link( $candidate ) ) {
                        $resolved = realpath( $candidate );
                        if ( $resolved !== false && ( $resolved === $makerGalaxyRoot || str_starts_with( $resolved, $makerGalaxyRoot . DIRECTORY_SEPARATOR ) ) ) {
                            $typeRocketMatches[$resolved] = true;
                        }
                    }
                }
            }
        }
    }
    $typeRocketMatches = array_keys( $typeRocketMatches );
    if ( count( $typeRocketMatches ) === 0 ) { $makerGalaxyFail( 'TypeRocket was not found; set MAKERMAKER_GALAXY_TYPEROCKET_PATH.' ); }
    if ( count( $typeRocketMatches ) > 1 ) { $makerGalaxyFail( 'TypeRocket discovery is ambiguous; set MAKERMAKER_GALAXY_TYPEROCKET_PATH explicitly.' ); }
    $makerGalaxyTypeRocket = $typeRocketMatches[0];
}
$makerGalaxyTypeRocket = $makerGalaxyRealDirectory( $makerGalaxyTypeRocket, 'TypeRocket' );
if ( ! is_file( $makerGalaxyTypeRocket . '/init.php' ) || ! is_dir( $makerGalaxyTypeRocket . '/vendor/typerocket/core' ) ) {
    $makerGalaxyFail( 'TypeRocket path lacks init.php or vendor/typerocket/core: ' . $makerGalaxyTypeRocket );
}
if ( $makerGalaxySlug !== null ) {
    define( 'MAKERMAKER_GALAXY_PLUGIN_SLUG', $makerGalaxySlug );
    define( 'MAKERMAKER_GALAXY_PLUGIN_NAMESPACE', $makerGalaxyNamespace );
    define( 'TYPEROCKET_GALAXY_MAKE_NAMESPACE', $makerGalaxyNamespace );
    define( 'TYPEROCKET_APP_ROOT_PATH', $makerGalaxyPlugin );
    define( 'TYPEROCKET_ALT_PATH', $makerGalaxyPlugin );
}
define( 'TYPEROCKET_GALAXY_PATH', $makerGalaxyTypeRocket );
define( 'TYPEROCKET_CORE_CONFIG_PATH', $makerGalaxyTypeRocket . '/config' );
define( 'TYPEROCKET_ROOT_WP', $makerGalaxyRoot . DIRECTORY_SEPARATOR );