#!/usr/bin/env php
<?php
if ( php_sapi_name() !== 'cli' ) { die( "Meant to be run from command line\n" ); }
define( 'TYPEROCKET_GALAXY', true );
require __DIR__ . '/galaxy-makermaker-config.php';
if ( ! defined( 'TYPEROCKET_GALAXY_FILE' ) ) { define( 'TYPEROCKET_GALAXY_FILE', __FILE__ ); }
require TYPEROCKET_GALAXY_PATH . '/init.php';
new \TypeRocket\Console\GalaxyConsoleLauncher();
