<?php
namespace Maker\MakerMaker\Generator;

use FilesystemIterator;
use Throwable;

final class ResourceGenerator
{
    private const REGISTRY = 'config/makermaker-resources.php';
    private const REGISTRY_HEADER = "<?php\n// Generated by MakerMaker. Add resources with the generator; do not discover them at runtime.\nreturn [\n";

    private readonly string $pluginDirectory;

    public function __construct( string $pluginDirectory )
    {
        if ( is_link( $pluginDirectory ) ) {
            throw new GeneratorException( 'Target plugin directory cannot be a symbolic link.' );
        }
        $root = realpath( $pluginDirectory );
        if ( $root === false || ! is_dir( $root ) || ! is_writable( $root ) ) {
            throw new GeneratorException( 'Target plugin directory is unavailable or not writable.' );
        }
        $this->pluginDirectory = $root;
    }

    public function generate( ResourceDefinition $definition ): ResourceGenerationResult
    {
        $files = $this->templates( $definition );
        $staging = $this->pluginDirectory . DIRECTORY_SEPARATOR . '.makermaker-resource-' . bin2hex( random_bytes( 6 ) );
        $lockPath = $this->pluginDirectory . DIRECTORY_SEPARATOR . '.makermaker-resource.lock';
        $lock = fopen( $lockPath, 'c+' );
        if ( $lock === false ) {
            throw new GeneratorException( 'Unable to create the resource generation lock.' );
        }

        $published = [];
        $createdDirectories = [];
        $registryBackup = null;
        try {
            if ( ! flock( $lock, LOCK_EX ) ) {
                throw new GeneratorException( 'Unable to lock the target plugin.' );
            }
            if ( ! mkdir( $staging, 0755 ) ) {
                throw new GeneratorException( 'Unable to create the resource staging directory.' );
            }

            $registryRelative = self::REGISTRY;
            $registryPath = $this->path( $registryRelative );
            $registry = $this->registryContents( $registryPath, $definition );
            $files[$registryRelative] = $registry;

            foreach ( array_keys( $files ) as $relative ) {
                $this->assertSafeDestination( $relative );
                if ( $relative !== $registryRelative && ( file_exists( $this->path( $relative ) ) || is_link( $this->path( $relative ) ) ) ) {
                    throw new GeneratorException( 'Refusing to overwrite existing file: ' . $relative );
                }
                $this->writeStaged( $staging, $relative, $files[$relative] );
            }

            foreach ( array_keys( $files ) as $relative ) {
                if ( $relative === $registryRelative ) {
                    continue;
                }
                $this->publish( $staging, $relative, $createdDirectories );
                $published[] = $relative;
            }

            if ( is_file( $registryPath ) ) {
                $registryBackup = $staging . DIRECTORY_SEPARATOR . '.registry-backup';
                if ( ! rename( $registryPath, $registryBackup ) ) {
                    throw new GeneratorException( 'Unable to stage the existing resource registry.' );
                }
            }
            $this->publish( $staging, $registryRelative, $createdDirectories );
            $published[] = $registryRelative;

            $this->removeTree( $staging );
            return new ResourceGenerationResult( $this->pluginDirectory, $definition, array_keys( $files ) );
        } catch ( Throwable $error ) {
            foreach ( array_reverse( $published ) as $relative ) {
                @unlink( $this->path( $relative ) );
            }
            if ( $registryBackup !== null && is_file( $registryBackup ) ) {
                @rename( $registryBackup, $this->path( self::REGISTRY ) );
            }
            foreach ( array_reverse( $createdDirectories ) as $directory ) {
                @rmdir( $directory );
            }
            $this->removeTree( $staging );
            if ( $error instanceof GeneratorException ) {
                throw $error;
            }
            throw new GeneratorException( 'Resource generation failed: ' . $error->getMessage(), 0, $error );
        } finally {
            flock( $lock, LOCK_UN );
            fclose( $lock );
            @unlink( $lockPath );
        }
    }

    /** @return array<string, string> */
    private function templates( ResourceDefinition $definition ): array
    {
        $name = $definition->name;
        $namespace = $definition->namespace;
        $key = $definition->key();
        $plural = $definition->pluralKey();
        $files = [
            "app/Models/{$name}.php" => "<?php\nnamespace {$namespace}\\Models;\n\nuse TypeRocket\\Models\\Model;\n\nfinal class {$name} extends Model\n{\n    protected \$resource = '{$plural}';\n}\n",
            "app/Controllers/{$name}Controller.php" => "<?php\nnamespace {$namespace}\\Controllers;\n\nuse TypeRocket\\Controllers\\Controller;\n\nfinal class {$name}Controller extends Controller\n{\n}\n",
            "app/Http/Fields/{$name}Fields.php" => "<?php\nnamespace {$namespace}\\Http\\Fields;\n\nuse TypeRocket\\Http\\Fields;\n\nfinal class {$name}Fields extends Fields\n{\n    protected function fillable(): array\n    {\n        return [];\n    }\n\n    protected function rules(): array\n    {\n        return [];\n    }\n}\n",
            "app/Auth/{$name}Policy.php" => "<?php\nnamespace {$namespace}\\Auth;\n\nuse TypeRocket\\Auth\\Policy;\nuse TypeRocket\\Models\\AuthUser;\n\nfinal class {$name}Policy extends Policy\n{\n    public function create(AuthUser \$auth, \$object): bool { return false; }\n    public function read(AuthUser \$auth, \$object): bool { return false; }\n    public function update(AuthUser \$auth, \$object): bool { return false; }\n    public function destroy(AuthUser \$auth, \$object): bool { return false; }\n}\n",
        ];

        if ( $definition->enabled( 'migration' ) ) {
            $files["database/migrations/create_{$plural}_table.php"] = "<?php\nuse TypeRocket\\Database\\Migration;\n\nreturn new class(\$wpdb) extends Migration\n{\n    public function up(): void\n    {\n        // Define the {$plural} table explicitly.\n    }\n\n    public function down(): void\n    {\n    }\n};\n";
        }
        if ( $definition->enabled( 'views' ) ) {
            $files["resources/views/{$plural}/index.php"] = "<?php defined( 'ABSPATH' ) || exit; ?>\n<div class=\"maker-resource maker-resource--{$key}\"></div>\n";
            $files["resources/views/{$plural}/form.php"] = "<?php defined( 'ABSPATH' ) || exit; ?>\n<div class=\"maker-resource-form maker-resource-form--{$key}\"></div>\n";
        }
        if ( $definition->enabled( 'factory' ) ) {
            $files["tests/Factories/{$name}Factory.php"] = "<?php\nnamespace {$namespace}\\Tests\\Factories;\n\nfinal class {$name}Factory\n{\n    /** @return array<string, mixed> */\n    public static function attributes(array \$overrides = []): array\n    {\n        return array_replace([], \$overrides);\n    }\n}\n";
        }
        if ( $definition->enabled( 'tests' ) ) {
            $files["tests/Unit/{$name}ResourceTest.php"] = "<?php\nnamespace {$namespace}\\Tests\\Unit;\n\nuse PHPUnit\\Framework\\TestCase;\n\nfinal class {$name}ResourceTest extends TestCase\n{\n    public function testResourceClassesAreLoadable(): void\n    {\n        self::assertTrue(class_exists(\\{$namespace}\\Models\\{$name}::class));\n        self::assertTrue(class_exists(\\{$namespace}\\Controllers\\{$name}Controller::class));\n    }\n}\n";
        }

        return $files;
    }

    private function registryContents( string $path, ResourceDefinition $definition ): string
    {
        if ( is_link( $path ) ) {
            throw new GeneratorException( 'Resource registry cannot be a symbolic link.' );
        }
        $contents = is_file( $path ) ? file_get_contents( $path ) : self::REGISTRY_HEADER . "];\n";
        if ( ! is_string( $contents ) || ! str_starts_with( $contents, self::REGISTRY_HEADER ) || ! str_ends_with( $contents, "];\n" ) ) {
            throw new GeneratorException( 'Existing resource registry is not in the MakerMaker managed format.' );
        }
        if ( str_contains( $contents, "    // Resource: {$definition->key()}\n" ) ) {
            throw new GeneratorException( 'Resource is already registered: ' . $definition->key() );
        }

        $namespace = '\\' . $definition->namespace;
        $name = $definition->name;
        $entry = "    // Resource: {$definition->key()}\n"
            . "    '{$definition->key()}' => [\n"
            . "        'model' => {$namespace}\\Models\\{$name}::class,\n"
            . "        'controller' => {$namespace}\\Controllers\\{$name}Controller::class,\n"
            . "        'fields' => {$namespace}\\Http\\Fields\\{$name}Fields::class,\n"
            . "        'policy' => {$namespace}\\Auth\\{$name}Policy::class,\n"
            . "    ],\n";

        return substr( $contents, 0, -3 ) . $entry . "];\n";
    }

    private function writeStaged( string $staging, string $relative, string $contents ): void
    {
        $path = $staging . DIRECTORY_SEPARATOR . str_replace( '/', DIRECTORY_SEPARATOR, $relative );
        $directory = dirname( $path );
        if ( ! is_dir( $directory ) && ! mkdir( $directory, 0755, true ) ) {
            throw new GeneratorException( 'Unable to create a staging directory.' );
        }
        if ( file_put_contents( $path, $contents, LOCK_EX ) === false ) {
            throw new GeneratorException( 'Unable to stage generated file: ' . $relative );
        }
    }

    /** @param list<string> $createdDirectories */
    private function publish( string $staging, string $relative, array &$createdDirectories ): void
    {
        $this->assertSafeDestination( $relative );
        $source = $staging . DIRECTORY_SEPARATOR . str_replace( '/', DIRECTORY_SEPARATOR, $relative );
        $destination = $this->path( $relative );
        $directory = dirname( $destination );
        $missing = [];
        while ( ! is_dir( $directory ) && $directory !== $this->pluginDirectory ) {
            $missing[] = $directory;
            $directory = dirname( $directory );
        }
        foreach ( array_reverse( $missing ) as $newDirectory ) {
            if ( ! mkdir( $newDirectory, 0755 ) && ! is_dir( $newDirectory ) ) {
                throw new GeneratorException( 'Unable to create generated file directory.' );
            }
            $createdDirectories[] = $newDirectory;
        }
        if ( ! link( $source, $destination ) ) {
            throw new GeneratorException( 'Unable to atomically publish generated file without overwrite: ' . $relative );
        }
        if ( ! unlink( $source ) ) {
            @unlink( $destination );
            throw new GeneratorException( 'Unable to finalize atomically published file: ' . $relative );
        }
    }

    private function path( string $relative ): string
    {
        return $this->pluginDirectory . DIRECTORY_SEPARATOR . str_replace( '/', DIRECTORY_SEPARATOR, $relative );
    }

    private function assertSafeDestination( string $relative ): void
    {
        if ( $relative === '' || str_contains( $relative, '..' ) || str_starts_with( $relative, '/' ) || str_contains( $relative, '\\' ) ) {
            throw new GeneratorException( 'Generated path is not a safe portable relative path.' );
        }
        $current = $this->pluginDirectory;
        $parts = explode( '/', $relative );
        array_pop( $parts );
        foreach ( $parts as $part ) {
            $current .= DIRECTORY_SEPARATOR . $part;
            if ( is_link( $current ) ) {
                throw new GeneratorException( 'Generated path contains a symbolic-link directory: ' . $relative );
            }
            if ( file_exists( $current ) && ! is_dir( $current ) ) {
                throw new GeneratorException( 'Generated path contains a non-directory component: ' . $relative );
            }
        }
    }

    private function removeTree( string $path ): void
    {
        if ( ! file_exists( $path ) && ! is_link( $path ) ) {
            return;
        }
        if ( is_file( $path ) || is_link( $path ) ) {
            @unlink( $path );
            return;
        }
        foreach ( new FilesystemIterator( $path, FilesystemIterator::SKIP_DOTS ) as $item ) {
            $this->removeTree( $item->getPathname() );
        }
        @rmdir( $path );
    }
}
