<?php
namespace Maker\MakerMaker\Generator;

use FilesystemIterator;
use Throwable;

final class ResourceGenerator
{
    private const REGISTRY = 'config/makermaker-resources.php';
    private const REGISTRY_HEADER = "<?php\n// Generated by MakerMaker. Add resources with the generator; do not discover them at runtime.\nreturn [\n";

    private readonly string $pluginDirectory;

    public function __construct( string $pluginDirectory )
    {
        if ( is_link( $pluginDirectory ) ) {
            throw new GeneratorException( 'Target plugin directory cannot be a symbolic link.' );
        }
        $root = realpath( $pluginDirectory );
        if ( $root === false || ! is_dir( $root ) || ! is_writable( $root ) ) {
            throw new GeneratorException( 'Target plugin directory is unavailable or not writable.' );
        }
        $this->pluginDirectory = $root;
    }

    public function generate( ResourceDefinition $definition ): ResourceGenerationResult
    {
        $files = $this->templates( $definition );
        $staging = $this->pluginDirectory . DIRECTORY_SEPARATOR . '.makermaker-resource-' . bin2hex( random_bytes( 6 ) );
        $lockPath = $this->pluginDirectory . DIRECTORY_SEPARATOR . '.makermaker-resource.lock';
        $lock = fopen( $lockPath, 'c+' );
        if ( $lock === false ) {
            throw new GeneratorException( 'Unable to create the resource generation lock.' );
        }

        $published = [];
        $createdDirectories = [];
        $registryBackup = null;
        try {
            if ( ! flock( $lock, LOCK_EX ) ) {
                throw new GeneratorException( 'Unable to lock the target plugin.' );
            }
            if ( ! mkdir( $staging, 0755 ) ) {
                throw new GeneratorException( 'Unable to create the resource staging directory.' );
            }

            $registryRelative = self::REGISTRY;
            $registryPath = $this->path( $registryRelative );
            $registry = $this->registryContents( $registryPath, $definition );
            $files[$registryRelative] = $registry;

            foreach ( array_keys( $files ) as $relative ) {
                $this->assertSafeDestination( $relative );
                if ( $relative !== $registryRelative && ( file_exists( $this->path( $relative ) ) || is_link( $this->path( $relative ) ) ) ) {
                    throw new GeneratorException( 'Refusing to overwrite existing file: ' . $relative );
                }
                $this->writeStaged( $staging, $relative, $files[$relative] );
            }

            foreach ( array_keys( $files ) as $relative ) {
                if ( $relative === $registryRelative ) {
                    continue;
                }
                $this->publish( $staging, $relative, $createdDirectories );
                $published[] = $relative;
            }

            if ( is_file( $registryPath ) ) {
                $registryBackup = $staging . DIRECTORY_SEPARATOR . '.registry-backup';
                if ( ! rename( $registryPath, $registryBackup ) ) {
                    throw new GeneratorException( 'Unable to stage the existing resource registry.' );
                }
            }
            $this->publish( $staging, $registryRelative, $createdDirectories );
            $published[] = $registryRelative;

            $this->removeTree( $staging );
            return new ResourceGenerationResult( $this->pluginDirectory, $definition, array_keys( $files ) );
        } catch ( Throwable $error ) {
            foreach ( array_reverse( $published ) as $relative ) {
                @unlink( $this->path( $relative ) );
            }
            if ( $registryBackup !== null && is_file( $registryBackup ) ) {
                @rename( $registryBackup, $this->path( self::REGISTRY ) );
            }
            foreach ( array_reverse( $createdDirectories ) as $directory ) {
                @rmdir( $directory );
            }
            $this->removeTree( $staging );
            if ( $error instanceof GeneratorException ) {
                throw $error;
            }
            throw new GeneratorException( 'Resource generation failed: ' . $error->getMessage(), 0, $error );
        } finally {
            flock( $lock, LOCK_UN );
            fclose( $lock );
            @unlink( $lockPath );
        }
    }

    /** @return array<string, string> */
    private function templates( ResourceDefinition $definition ): array
    {
        $name = $definition->name;
        $namespace = $definition->namespace;
        $key = $definition->key();
        $plural = $definition->pluralKey();
        $tokens = [
            '{{namespace}}' => $namespace,
            '{{name}}' => $name,
            '{{key}}' => $key,
            '{{plural}}' => $plural,
            '{{title}}' => ucwords( str_replace( '_', ' ', $plural ) ),
            '{{singular_title}}' => ucwords( str_replace( '_', ' ', $key ) ),
            '{{variable}}' => lcfirst( $name ),
        ];
        $files = [
            "app/Models/{$name}.php" => $this->render( <<<'PHP'
<?php
namespace {{namespace}}\Models;

use TypeRocket\Models\Model;

final class {{name}} extends Model
{
    protected $resource = '{{plural}}';
    protected $fillable = [ 'name', 'description', 'is_active', 'sort_order' ];
    protected $guard = [ 'id', 'created_at', 'updated_at', 'deleted_at', 'created_by', 'updated_by' ];
}
PHP, $tokens ),
            "app/Controllers/{$name}Controller.php" => $this->render( <<<'PHP'
<?php
namespace {{namespace}}\Controllers;

use {{namespace}}\Http\Fields\{{name}}Fields;
use {{namespace}}\Models\{{name}};
use {{namespace}}\View;
use TypeRocket\Controllers\Controller;
use TypeRocket\Http\Response;

final class {{name}}Controller extends Controller
{
    public function index()
    {
        return View::new('{{plural}}.index');
    }

    public function add()
    {
        $form = tr_form({{name}}::class)->useErrors()->useOld()->useConfirm();
        return View::new('{{plural}}.form', compact('form'));
    }

    public function create({{name}}Fields $fields, {{name}} ${{variable}}, Response $response)
    {
        ${{variable}}->save($fields);
        if (${{variable}}->getErrors()) {
            $response->flashNext('{{singular_title}} creation failed', 'error');
            return tr_redirect()->back()->withErrors(${{variable}}->getErrors());
        }
        $response->flashNext('{{singular_title}} created', 'success');
        return tr_redirect()->toPage('{{key}}', 'index');
    }

    public function edit({{name}} ${{variable}})
    {
        $form = tr_form(${{variable}})->useErrors()->useOld()->useConfirm();
        $current_id = ${{variable}}->getID();
        return View::new('{{plural}}.form', compact('form', 'current_id'));
    }

    public function update({{name}} ${{variable}}, {{name}}Fields $fields, Response $response)
    {
        ${{variable}}->save($fields);
        if (${{variable}}->getErrors()) {
            $response->flashNext('{{singular_title}} update failed', 'error');
            return tr_redirect()->back()->withErrors(${{variable}}->getErrors());
        }
        $response->flashNext('{{singular_title}} updated', 'success');
        return tr_redirect()->toPage('{{key}}', 'edit', ${{variable}}->getID());
    }

    public function show({{name}} ${{variable}})
    {
        return ${{variable}};
    }

    public function delete({{name}} ${{variable}})
    {
        return ${{variable}};
    }

    public function destroy({{name}} ${{variable}}, Response $response)
    {
        if (${{variable}}->delete() === false) {
            return $response->error('{{singular_title}} deletion failed')->setStatus(500);
        }
        $response->flashNext('{{singular_title}} deleted', 'success');
        return tr_redirect()->toPage('{{key}}', 'index');
    }
}
PHP, $tokens ),
            "app/Http/Fields/{$name}Fields.php" => $this->render( <<<'PHP'
<?php
namespace {{namespace}}\Http\Fields;

use TypeRocket\Http\Fields;

final class {{name}}Fields extends Fields
{
    protected $run = true;

    protected function fillable(): array
    {
        return [ 'name', 'description', 'is_active', 'sort_order' ];
    }

    protected function rules(): array
    {
        return [
            'name' => 'required|max:255',
            'description' => '?max:65535',
            'is_active' => 'boolean',
            'sort_order' => 'integer|min:0',
        ];
    }
}
PHP, $tokens ),
            "app/Auth/{$name}Policy.php" => "<?php\nnamespace {$namespace}\\Auth;\n\nuse TypeRocket\\Auth\\Policy;\nuse TypeRocket\\Models\\AuthUser;\n\nfinal class {$name}Policy extends Policy\n{\n    public function create(AuthUser \$auth, \$object): bool { return false; }\n    public function read(AuthUser \$auth, \$object): bool { return false; }\n    public function update(AuthUser \$auth, \$object): bool { return false; }\n    public function destroy(AuthUser \$auth, \$object): bool { return false; }\n}\n",
        ];

        if ( $definition->enabled( 'migration' ) ) {
            $timestamp = time();
            $files["database/migrations/{$timestamp}.create_{$plural}_table.sql"] = $this->render( <<<'SQL'
-- Description: Create {{plural}} table
-- >>> Up >>>
CREATE TABLE IF NOT EXISTS `{!!prefix!!}{{plural}}` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `description` text DEFAULT NULL,
  `is_active` tinyint(1) unsigned NOT NULL DEFAULT 1,
  `sort_order` int unsigned NOT NULL DEFAULT 0,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  `updated_at` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `deleted_at` datetime DEFAULT NULL,
  `created_by` bigint(20) unsigned DEFAULT NULL,
  `updated_by` bigint(20) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_{{plural}}__name` (`name`),
  KEY `idx_{{plural}}__active_order` (`is_active`, `sort_order`),
  KEY `idx_{{plural}}__deleted_at` (`deleted_at`),
  KEY `idx_{{plural}}__created_by` (`created_by`),
  KEY `idx_{{plural}}__updated_by` (`updated_by`),
  CONSTRAINT `fk_{{plural}}__created_by` FOREIGN KEY (`created_by`) REFERENCES `{!!prefix!!}users` (`ID`) ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT `fk_{{plural}}__updated_by` FOREIGN KEY (`updated_by`) REFERENCES `{!!prefix!!}users` (`ID`) ON UPDATE CASCADE ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='{{title}}';

-- >>> Down >>>
DROP TABLE IF EXISTS `{!!prefix!!}{{plural}}`;
SQL, $tokens );
        }
        if ( $definition->enabled( 'views' ) ) {
            $files["resources/views/{$plural}/index.php"] = $this->render( <<<'PHP'
<?php

use {{namespace}}\Models\{{name}};

$table = tr_table({{name}}::class);
$table->setBulkActions(tr_form()->useConfirm(), []);
$table->setColumns([
    'name' => [
        'label' => 'Name',
        'sort' => true,
        'actions' => ['edit', 'view', 'delete'],
    ],
    'is_active' => [
        'label' => 'Active',
        'sort' => true,
    ],
    'sort_order' => [
        'label' => 'Sort Order',
        'sort' => true,
    ],
    'created_at' => [
        'label' => 'Created At',
        'sort' => true,
    ],
    'updated_at' => [
        'label' => 'Updated At',
        'sort' => true,
    ],
    'id' => [
        'label' => 'ID',
        'sort' => true,
    ],
], 'name')->setOrder('id', 'DESC')->render();
PHP, $tokens );
            $files["resources/views/{$plural}/form.php"] = $this->render( <<<'PHP'
<?php

echo $form->open();

$tabs = tr_tabs()
    ->setFooter($form->save('Save {{singular_title}}'))
    ->layoutLeft();

$tabs->tab('Overview', 'admin-settings', [
    $form->fieldset(
        '{{singular_title}} Details',
        'Core {{singular_title}} information',
        [
            $form->text('name')
                ->setLabel('Name')
                ->setHelp('Enter the {{singular_title}} name')
                ->setAttribute('maxlength', '255')
                ->markLabelRequired(),
            $form->textarea('description')
                ->setLabel('Description')
                ->setHelp('Describe this {{singular_title}}')
                ->setAttribute('rows', '4'),
            $form->toggle('is_active')
                ->setLabel('Active')
                ->setHelp('Whether this {{singular_title}} is active'),
            $form->number('sort_order')
                ->setLabel('Sort Order')
                ->setHelp('Lower numbers appear first')
                ->setAttribute('min', '0')
                ->setAttribute('step', '1')
                ->setDefault('0'),
        ]
    ),
])->setDescription('{{singular_title}}');

if (isset($current_id)) {
    $tabs->tab('System', 'info', [
        $form->fieldset(
            'System Information',
            'Read-only record and audit metadata',
            [
                $form->row()
                    ->withColumn(
                        $form->text('id')
                            ->setLabel('ID')
                            ->setHelp('System-generated record ID')
                            ->setAttribute('readonly', true)
                            ->setAttribute('name', false)
                    )
                    ->withColumn(
                        $form->text('deleted_at')
                            ->setLabel('Deleted At')
                            ->setHelp('Soft-deletion timestamp, when applicable')
                            ->setAttribute('readonly', true)
                            ->setAttribute('name', false)
                    ),
                $form->row()
                    ->withColumn(
                        $form->text('created_at')
                            ->setLabel('Created At')
                            ->setHelp('Record creation timestamp')
                            ->setAttribute('readonly', true)
                            ->setAttribute('name', false)
                    )
                    ->withColumn(
                        $form->text('updated_at')
                            ->setLabel('Updated At')
                            ->setHelp('Last update timestamp')
                            ->setAttribute('readonly', true)
                            ->setAttribute('name', false)
                    ),
                $form->row()
                    ->withColumn(
                        $form->text('created_by')
                            ->setLabel('Created By')
                            ->setHelp('WordPress user ID that created this record')
                            ->setAttribute('readonly', true)
                            ->setAttribute('name', false)
                    )
                    ->withColumn(
                        $form->text('updated_by')
                            ->setLabel('Last Updated By')
                            ->setHelp('WordPress user ID that last updated this record')
                            ->setAttribute('readonly', true)
                            ->setAttribute('name', false)
                    ),
            ]
        ),
    ])->setDescription('System Information');
}

$tabs->render();

echo $form->close();
PHP, $tokens );
        }
        if ( $definition->enabled( 'factory' ) ) {
            $files["tests/Factories/{$name}Factory.php"] = "<?php\nnamespace {$namespace}\\Tests\\Factories;\n\nfinal class {$name}Factory\n{\n    /** @return array<string, mixed> */\n    public static function attributes(array \$overrides = []): array\n    {\n        return array_replace([], \$overrides);\n    }\n}\n";
        }
        if ( $definition->enabled( 'tests' ) ) {
            $files["tests/Unit/{$name}ResourceTest.php"] = "<?php\nnamespace {$namespace}\\Tests\\Unit;\n\nuse PHPUnit\\Framework\\TestCase;\n\nfinal class {$name}ResourceTest extends TestCase\n{\n    public function testResourceClassesAreLoadable(): void\n    {\n        self::assertTrue(class_exists(\\{$namespace}\\Models\\{$name}::class));\n        self::assertTrue(class_exists(\\{$namespace}\\Controllers\\{$name}Controller::class));\n    }\n}\n";
        }

        return $files;
    }

    /** @param array<string, string> $tokens */
    private function render( string $template, array $tokens ): string
    {
        return str_replace( array_keys( $tokens ), array_values( $tokens ), $template ) . "\n";
    }

    private function registryContents( string $path, ResourceDefinition $definition ): string
    {
        if ( is_link( $path ) ) {
            throw new GeneratorException( 'Resource registry cannot be a symbolic link.' );
        }
        $contents = is_file( $path ) ? file_get_contents( $path ) : self::REGISTRY_HEADER . "];\n";
        if ( ! is_string( $contents ) || ! str_starts_with( $contents, self::REGISTRY_HEADER ) || ! str_ends_with( $contents, "];\n" ) ) {
            throw new GeneratorException( 'Existing resource registry is not in the MakerMaker managed format.' );
        }
        if ( str_contains( $contents, "    // Resource: {$definition->key()}\n" ) ) {
            throw new GeneratorException( 'Resource is already registered: ' . $definition->key() );
        }

        $namespace = '\\' . $definition->namespace;
        $name = $definition->name;
        $plural = $definition->pluralKey();
        $title = ucwords( str_replace( '_', ' ', $plural ) );
        $capabilities = '';
        foreach ( [ 'manage', 'edit', 'delete', 'view', 'publish' ] as $action ) {
            $capabilities .= "            '{$action}_{$plural}',\n";
        }
        $entry = "    // Resource: {$definition->key()}\n"
            . "    '{$definition->key()}' => [\n"
            . "        'name' => '{$name}',\n"
            . "        'title' => '{$title}',\n"
            . "        'icon' => 'admin-generic',\n"
            . "        'position' => 25,\n"
            . "        'capabilities' => [\n{$capabilities}        ],\n"
            . "        'model' => {$namespace}\\Models\\{$name}::class,\n"
            . "        'controller' => {$namespace}\\Controllers\\{$name}Controller::class,\n"
            . "        'fields' => {$namespace}\\Http\\Fields\\{$name}Fields::class,\n"
            . "        'policy' => {$namespace}\\Auth\\{$name}Policy::class,\n"
            . "    ],\n";

        return substr( $contents, 0, -3 ) . $entry . "];\n";
    }

    private function writeStaged( string $staging, string $relative, string $contents ): void
    {
        $path = $staging . DIRECTORY_SEPARATOR . str_replace( '/', DIRECTORY_SEPARATOR, $relative );
        $directory = dirname( $path );
        if ( ! is_dir( $directory ) && ! mkdir( $directory, 0755, true ) ) {
            throw new GeneratorException( 'Unable to create a staging directory.' );
        }
        if ( file_put_contents( $path, $contents, LOCK_EX ) === false ) {
            throw new GeneratorException( 'Unable to stage generated file: ' . $relative );
        }
    }

    /** @param list<string> $createdDirectories */
    private function publish( string $staging, string $relative, array &$createdDirectories ): void
    {
        $this->assertSafeDestination( $relative );
        $source = $staging . DIRECTORY_SEPARATOR . str_replace( '/', DIRECTORY_SEPARATOR, $relative );
        $destination = $this->path( $relative );
        $directory = dirname( $destination );
        $missing = [];
        while ( ! is_dir( $directory ) && $directory !== $this->pluginDirectory ) {
            $missing[] = $directory;
            $directory = dirname( $directory );
        }
        foreach ( array_reverse( $missing ) as $newDirectory ) {
            if ( ! mkdir( $newDirectory, 0755 ) && ! is_dir( $newDirectory ) ) {
                throw new GeneratorException( 'Unable to create generated file directory.' );
            }
            $createdDirectories[] = $newDirectory;
        }
        if ( ! link( $source, $destination ) ) {
            throw new GeneratorException( 'Unable to atomically publish generated file without overwrite: ' . $relative );
        }
        if ( ! unlink( $source ) ) {
            @unlink( $destination );
            throw new GeneratorException( 'Unable to finalize atomically published file: ' . $relative );
        }
    }

    private function path( string $relative ): string
    {
        return $this->pluginDirectory . DIRECTORY_SEPARATOR . str_replace( '/', DIRECTORY_SEPARATOR, $relative );
    }

    private function assertSafeDestination( string $relative ): void
    {
        if ( $relative === '' || str_contains( $relative, '..' ) || str_starts_with( $relative, '/' ) || str_contains( $relative, '\\' ) ) {
            throw new GeneratorException( 'Generated path is not a safe portable relative path.' );
        }
        $current = $this->pluginDirectory;
        $parts = explode( '/', $relative );
        array_pop( $parts );
        foreach ( $parts as $part ) {
            $current .= DIRECTORY_SEPARATOR . $part;
            if ( is_link( $current ) ) {
                throw new GeneratorException( 'Generated path contains a symbolic-link directory: ' . $relative );
            }
            if ( file_exists( $current ) && ! is_dir( $current ) ) {
                throw new GeneratorException( 'Generated path contains a non-directory component: ' . $relative );
            }
        }
    }

    private function removeTree( string $path ): void
    {
        if ( ! file_exists( $path ) && ! is_link( $path ) ) {
            return;
        }
        if ( is_file( $path ) || is_link( $path ) ) {
            @unlink( $path );
            return;
        }
        foreach ( new FilesystemIterator( $path, FilesystemIterator::SKIP_DOTS ) as $item ) {
            $this->removeTree( $item->getPathname() );
        }
        @rmdir( $path );
    }
}
